name = "ValueInferenceTools"
uuid = "5ede3950-d1bc-5508-9a1e-a2d7a859d5ef"
authors = ["Pietro Vertechi <pietro.vertechi@neuro.fchampalimaud.org>"]
version = "0.1.0"

[deps]
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
